name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout del código
        uses: actions/checkout@v4 # Actualizado a la última versión

      # Paso 2: Configurar JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven 

      # 3. Ejecutar el build y las pruebas
      - name: Build and Test
        run: mvn clean verify

      # 4. Ejecutar Checkstyle
      - name: Checkstyle Analysis
        run: mvn checkstyle:checkstyle
      - name: Output Checkstyle Results
        if: always() # Para siempre mostrar resultados
        run: cat target/checkstyle-result.xml || echo "Checkstyle report not found"

      # 5. Ejecutar SpotBugs
      - name: SpotBugs Analysis
        run: mvn spotbugs:spotbugs
      - name: Output SpotBugs Results
        if: always()
        run: cat target/spotbugsXml.xml || echo "SpotBugs report not found"

      # 6. Generar reporte de cobertura con JaCoCo
      - name: Generate Coverage Report
        run: mvn jacoco:report
      - name: Output JaCoCo Coverage Report
        if: always()
        run: cat target/site/jacoco/jacoco.xml || echo "JaCoCo coverage report not found"

      # Paso 7: Subir artefactos generados
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Maven-Reports
          path: |
            target/site/jacoco/jacoco.xml
            target/checkstyle-result.xml
            target/spotbugsXml.xml
